local LOC = require("languages/loc")
local lang_id = LOC:GetLanguage()
local STRINGS = GLOBAL.STRINGS
-- print(lang_id,"----------------------")
if lang_id == 22 or lang_id == 21 then
    STRINGS.NAMES.SPICE_BONE = "骨粉"
    STRINGS.NAMES.SPICE_BONE_FOOD = "浓香{food}"

    STRINGS.NAMES.SPICE_GLOM = "格罗姆粉"
    STRINGS.NAMES.SPICE_GLOM_FOOD = "格罗姆{food}"

    STRINGS.NAMES.SPICE_SHELL = "壳粉"
    STRINGS.NAMES.SPICE_SHELL_FOOD = "切割机壳{food}"
else
    STRINGS.NAMES.SPICE_BONE = "Bone Powder"
    STRINGS.NAMES.SPICE_BONE_FOOD = "Fragrant{food}"

    STRINGS.NAMES.SPICE_GLOM = "Glommer Powder"
    STRINGS.NAMES.SPICE_GLOM_FOOD = "Glommer{food}"

    STRINGS.NAMES.SPICE_SHELL = "Shell Powder"
    STRINGS.NAMES.SPICE_SHELL_FOOD = "Shell{food}"
end

-- 牛角粉
STRINGS.RECIPE_DESC.SPICE_BONE = STRINGS.RECIPE_DESC.BALLOONSPEED
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPICE_BONE = STRINGS.CHARACTERS.GENERIC.DESCRIBE.CATCOONDEN.EMPTY

-- 格罗姆粉
STRINGS.RECIPE_DESC.SPICE_GLOM = STRINGS.CHARACTERS.WEBBER.DESCRIBE.QUAGMIRE_SAP
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPICE_GLOM = STRINGS.CHARACTERS.WAXWELL.DESCRIBE.KELP

-- 饼干切割机壳粉
STRINGS.RECIPE_DESC.SPICE_SHELL = STRINGS.CHARACTERS.WANDA.DESCRIBE.COOKIECUTTERSHELL
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPICE_SHELL = STRINGS.CHARACTERS.WILLOW.DESCRIBE.COOKIECUTTERHAT

-- 骨粉buff
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ATTACH_BUFF_STRONG_FOR_HEAVY = STRINGS.CHARACTERS.WOODIE.DESCRIBE.SLINGSHOTAMMO_SLOW
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_DETACH_BUFF_STRONG_FOR_HEAVY = STRINGS.CHARACTERS.WORTOX.DESCRIBE.YOTC_CARRAT_GYM_STAMINA.GENERIC

-- 格罗姆buff
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ATTACH_BUFF_STRONGGRIP_STATE = STRINGS.CHARACTERS.WOODIE.ANNOUNCE_CANT_ESCAPE_CURSE
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_DETACH_BUFF_STRONGGRIP_STATE = STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_IS_FEASTING

-- 壳粉buff
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ATTACH_BUFF_DAMAGE_REFLECTION = STRINGS.CHARACTERS.WARLY.DESCRIBE.HOUNDSTOOTH_BLOWPIPE
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_DETACH_BUFF_DAMAGE_REFLECTION = STRINGS.CHARACTERS.WATHGRITHR.ANNOUNCE_DETACH_BUFF_PLAYERABSORPTION

-- 黄油
STRINGS.RECIPE_DESC.WANDERINGTRADERSHOP_BUTTER = STRINGS.CHARACTERS.WEBBER.DESCRIBE.BUTTER

-- 种子包
STRINGS.NAMES.WARLY_SEEDPACKET = STRINGS.NAMES.YOTC_SEEDPACKET
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WARLY_SEEDPACKET = STRINGS.SKIN_DESCRIPTIONS.loading_warly2_trailer

-- STRINGS.RECIPE_DESC.WARLY_SEEDPACKET = STRINGS.CHARACTERS.WEBBER.DESCRIBE.BUTTER
